unit uPSI_ucEmutecaSoftManager;
{
This file has been generated by UnitParser v0.7, written by M. Knight
and updated by NP. v/d Spek and George Birbilis. 
Source Code from Carlo Kok has been used to implement various sections of
UnitParser. Components of ROPS are used in the construction of UnitParser,
code implementing the class wrapper is taken from Carlo Kok's conv utility

}
interface
 
uses
   SysUtils
  ,Classes
  ,uPSComponent
  ,uPSRuntime
  ,uPSCompiler
  ;
 
type 
(*----------------------------------------------------------------------------*)
  TPSImport_ucEmutecaSoftManager = class(TPSPlugin)
  protected
    procedure CompileImport1(CompExec: TPSScript); override;
    procedure ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter); override;
  end;
 
 
{ compile-time registration functions }
procedure SIRegister_cEmutecaSoftManager(CL: TPSPascalCompiler);
procedure SIRegister_ucEmutecaSoftManager(CL: TPSPascalCompiler);

{ run-time registration functions }
procedure RIRegister_cEmutecaSoftManager(CL: TPSRuntimeClassImporter);
procedure RIRegister_ucEmutecaSoftManager(CL: TPSRuntimeClassImporter);

procedure Register;

implementation


uses
   fgl
  ,LazUTF8
  ,LazFileUtils
  ,IniFiles
  ,uEmutecaCommon
  ,uaEmutecaCustomManager
  ,uaEmutecaCustomSystem
  ,uaEmutecaCustomGroup
  ,ucEmutecaSoftList
  ,ucEmutecaSoftManager
  ;
 
 
procedure Register;
begin
  RegisterComponents('Pascal Script', [TPSImport_ucEmutecaSoftManager]);
end;

(* === compile-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure SIRegister_cEmutecaSoftManager(CL: TPSPascalCompiler);
begin
  //with RegClassS(CL,'caEmutecaCustomManager', 'cEmutecaSoftManager') do
  with CL.AddClassN(CL.FindClass('caEmutecaCustomManager'),'cEmutecaSoftManager') do
  begin
    RegisterMethod('Procedure ClearData');
    RegisterMethod('Procedure LoadData');
    RegisterProperty('System', 'caEmutecaCustomSystem', iptrw);
    RegisterProperty('FilterGroup', 'caEmutecaCustomGroup', iptrw);
    RegisterProperty('VisibleList', 'cEmutecaSoftList', iptr);
    RegisterProperty('FullList', 'cEmutecaSoftList', iptr);
  end;
end;

(*----------------------------------------------------------------------------*)
procedure SIRegister_ucEmutecaSoftManager(CL: TPSPascalCompiler);
begin
  SIRegister_cEmutecaSoftManager(CL);
end;

(* === run-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure cEmutecaSoftManagerFullList_R(Self: cEmutecaSoftManager; var T: cEmutecaSoftList);
begin T := Self.FullList; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaSoftManagerVisibleList_R(Self: cEmutecaSoftManager; var T: cEmutecaSoftList);
begin T := Self.VisibleList; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaSoftManagerFilterGroup_W(Self: cEmutecaSoftManager; const T: caEmutecaCustomGroup);
begin Self.FilterGroup := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaSoftManagerFilterGroup_R(Self: cEmutecaSoftManager; var T: caEmutecaCustomGroup);
begin T := Self.FilterGroup; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaSoftManagerSystem_W(Self: cEmutecaSoftManager; const T: caEmutecaCustomSystem);
begin Self.System := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaSoftManagerSystem_R(Self: cEmutecaSoftManager; var T: caEmutecaCustomSystem);
begin T := Self.System; end;

(*----------------------------------------------------------------------------*)
procedure RIRegister_cEmutecaSoftManager(CL: TPSRuntimeClassImporter);
begin
  with CL.Add(cEmutecaSoftManager) do
  begin
    RegisterMethod(@cEmutecaSoftManager.ClearData, 'ClearData');
//    RegisterMethod(@cEmutecaSoftManager.LoadData, 'LoadData');
    RegisterPropertyHelper(@cEmutecaSoftManagerSystem_R,@cEmutecaSoftManagerSystem_W,'System');
    RegisterPropertyHelper(@cEmutecaSoftManagerFilterGroup_R,@cEmutecaSoftManagerFilterGroup_W,'FilterGroup');
    RegisterPropertyHelper(@cEmutecaSoftManagerVisibleList_R,nil,'VisibleList');
    RegisterPropertyHelper(@cEmutecaSoftManagerFullList_R,nil,'FullList');
  end;
end;

(*----------------------------------------------------------------------------*)
procedure RIRegister_ucEmutecaSoftManager(CL: TPSRuntimeClassImporter);
begin
  RIRegister_cEmutecaSoftManager(CL);
end;

 
 
{ TPSImport_ucEmutecaSoftManager }
(*----------------------------------------------------------------------------*)
procedure TPSImport_ucEmutecaSoftManager.CompileImport1(CompExec: TPSScript);
begin
  SIRegister_ucEmutecaSoftManager(CompExec.Comp);
end;
(*----------------------------------------------------------------------------*)
procedure TPSImport_ucEmutecaSoftManager.ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter);
begin
  RIRegister_ucEmutecaSoftManager(ri);
end;
(*----------------------------------------------------------------------------*)
 
 
end.
