unit uPSI_ucEmutecaSystem;
{
This file has been generated by UnitParser v0.7, written by M. Knight
and updated by NP. v/d Spek and George Birbilis. 
Source Code from Carlo Kok has been used to implement various sections of
UnitParser. Components of ROPS are used in the construction of UnitParser,
code implementing the class wrapper is taken from Carlo Kok's conv utility

}
interface
 
uses
   SysUtils
  ,Classes
  ,uPSComponent
  ,uPSRuntime
  ,uPSCompiler
  ;
 
type 
(*----------------------------------------------------------------------------*)
  TPSImport_ucEmutecaSystem = class(TPSPlugin)
  protected
    procedure CompileImport1(CompExec: TPSScript); override;
    procedure ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter); override;
  end;
 
 
{ compile-time registration functions }
procedure SIRegister_cEmutecaSystem(CL: TPSPascalCompiler);
procedure SIRegister_ucEmutecaSystem(CL: TPSPascalCompiler);

{ run-time registration functions }
procedure RIRegister_cEmutecaSystem(CL: TPSRuntimeClassImporter);
procedure RIRegister_ucEmutecaSystem(CL: TPSRuntimeClassImporter);

procedure Register;

implementation


uses
   LazFileUtils
  ,LazUTF8
  ,uEmutecaCommon
  ,uaEmutecaCustomSystem
  ,ucEmutecaGroupManager
  ,ucEmutecaGroupList
  ,ucEmutecaGroup
  ,ucEmutecaSoftManager
  ,ucEmutecaSoftList
  ,ucEmutecaSoftware
  ,ucEmutecaSystem
  ;
 
 
procedure Register;
begin
  RegisterComponents('Pascal Script', [TPSImport_ucEmutecaSystem]);
end;

(* === compile-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure SIRegister_cEmutecaSystem(CL: TPSPascalCompiler);
begin
  //with RegClassS(CL,'caEmutecaCustomSystem', 'cEmutecaSystem') do
  with CL.AddClassN(CL.FindClass('caEmutecaCustomSystem'),'cEmutecaSystem') do
  begin
    RegisterProperty('ProgressCallBack', 'TEmutecaProgressCallBack', iptrw);
    RegisterMethod('Procedure AddSoft( aSoft : cEmutecaSoftware)');
    RegisterMethod('Procedure LoadSoftGroupLists( aFile : string)');
    RegisterMethod('Procedure ImportSoftGroupLists( aFile : string)');
    RegisterMethod('Procedure SaveSoftGroupLists( aFile : string; ExportMode : boolean)');
    RegisterProperty('GroupManager', 'cEmutecaGroupManager', iptr);
    RegisterProperty('SoftManager', 'cEmutecaSoftManager', iptr);
  end;
end;

(*----------------------------------------------------------------------------*)
procedure SIRegister_ucEmutecaSystem(CL: TPSPascalCompiler);
begin
  SIRegister_cEmutecaSystem(CL);
  CL.AddTypeS('TEmutecaReturnSystemCB', 'Function ( aSystem : cEmutecaSystem) :'
   +' boolean');
end;

(* === run-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure cEmutecaSystemSoftManager_R(Self: cEmutecaSystem; var T: cEmutecaSoftManager);
begin T := Self.SoftManager; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaSystemGroupManager_R(Self: cEmutecaSystem; var T: cEmutecaGroupManager);
begin T := Self.GroupManager; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaSystemProgressCallBack_W(Self: cEmutecaSystem; const T: TEmutecaProgressCallBack);
begin Self.ProgressCallBack := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaSystemProgressCallBack_R(Self: cEmutecaSystem; var T: TEmutecaProgressCallBack);
begin T := Self.ProgressCallBack; end;

(*----------------------------------------------------------------------------*)
procedure RIRegister_cEmutecaSystem(CL: TPSRuntimeClassImporter);
begin
  with CL.Add(cEmutecaSystem) do
  begin
    RegisterPropertyHelper(@cEmutecaSystemProgressCallBack_R,@cEmutecaSystemProgressCallBack_W,'ProgressCallBack');
    RegisterMethod(@cEmutecaSystem.AddSoft, 'AddSoft');
    RegisterMethod(@cEmutecaSystem.LoadSoftGroupLists, 'LoadSoftGroupLists');
    RegisterMethod(@cEmutecaSystem.ImportSoftGroupLists, 'ImportSoftGroupLists');
    RegisterMethod(@cEmutecaSystem.SaveSoftGroupLists, 'SaveSoftGroupLists');
    RegisterPropertyHelper(@cEmutecaSystemGroupManager_R,nil,'GroupManager');
    RegisterPropertyHelper(@cEmutecaSystemSoftManager_R,nil,'SoftManager');
  end;
end;

(*----------------------------------------------------------------------------*)
procedure RIRegister_ucEmutecaSystem(CL: TPSRuntimeClassImporter);
begin
  RIRegister_cEmutecaSystem(CL);
end;

 
 
{ TPSImport_ucEmutecaSystem }
(*----------------------------------------------------------------------------*)
procedure TPSImport_ucEmutecaSystem.CompileImport1(CompExec: TPSScript);
begin
  SIRegister_ucEmutecaSystem(CompExec.Comp);
end;
(*----------------------------------------------------------------------------*)
procedure TPSImport_ucEmutecaSystem.ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter);
begin
  RIRegister_ucEmutecaSystem(ri);
end;
(*----------------------------------------------------------------------------*)
 
 
end.
