unit uPSI_ucEmutecaEmulator;
{
This file has been generated by UnitParser v0.7, written by M. Knight
and updated by NP. v/d Spek and George Birbilis. 
Source Code from Carlo Kok has been used to implement various sections of
UnitParser. Components of ROPS are used in the construction of UnitParser,
code implementing the class wrapper is taken from Carlo Kok's conv utility

}
interface
 
uses
   SysUtils
  ,Classes
  ,uPSComponent
  ,uPSRuntime
  ,uPSCompiler
  ;
 
type 
(*----------------------------------------------------------------------------*)
  TPSImport_ucEmutecaEmulator = class(TPSPlugin)
  protected
    procedure CompileImport1(CompExec: TPSScript); override;
    procedure ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter); override;
  end;
 
 
{ compile-time registration functions }
procedure SIRegister_cEmutecaEmulator(CL: TPSPascalCompiler);
procedure SIRegister_ucEmutecaEmulator(CL: TPSPascalCompiler);

{ run-time registration functions }
procedure RIRegister_cEmutecaEmulator(CL: TPSRuntimeClassImporter);
procedure RIRegister_ucEmutecaEmulator(CL: TPSRuntimeClassImporter);

procedure Register;

implementation


uses
   FileUtil
  ,StrUtils
  ,LazUTF8
  ,LazFileUtils
  ,IniFiles
  ,uCHXStrUtils
  ,ucEmutecaPlayingStats
  ,ucEmutecaEmulator
  ;
 
 
procedure Register;
begin
  RegisterComponents('Pascal Script', [TPSImport_ucEmutecaEmulator]);
end;

(* === compile-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure SIRegister_cEmutecaEmulator(CL: TPSPascalCompiler);
begin
  //with RegClassS(CL,'TComponent', 'cEmutecaEmulator') do
  with CL.AddClassN(CL.FindClass('TComponent'),'cEmutecaEmulator') do
  begin
    RegisterMethod('Function Execute( GameFile : string) : integer');
    RegisterMethod('Function ExecuteAlone : integer');
    RegisterMethod('Procedure LoadFromIni( aIniFile : TCustomIniFile)');
    RegisterMethod('Procedure SaveToIni( aIniFile : TCustomIniFile; const ExportMode : boolean)');
    RegisterProperty('ID', 'string', iptrw);
    RegisterProperty('Enabled', 'boolean', iptrw);
    RegisterProperty('EmulatorName', 'string', iptrw);
    RegisterProperty('ExeFile', 'string', iptrw);
    RegisterProperty('WorkingFolder', 'string', iptrw);
    RegisterProperty('Parameters', 'string', iptrw);
    RegisterProperty('FileExt', 'TStringList', iptrw);
    RegisterProperty('ExitCode', 'integer', iptrw);
    RegisterProperty('Developer', 'string', iptrw);
    RegisterProperty('WebPage', 'string', iptrw);
    RegisterProperty('Icon', 'string', iptrw);
    RegisterProperty('Image', 'string', iptrw);
    RegisterProperty('InfoFile', 'string', iptrw);
    RegisterProperty('Stats', 'cEmutecaPlayingStats', iptr);
  end;
end;

(*----------------------------------------------------------------------------*)
procedure SIRegister_ucEmutecaEmulator(CL: TPSPascalCompiler);
begin
 CL.AddConstantN('krsEmulatorEnabledKey','String').SetString( 'Enabled');
 CL.AddConstantN('krsEmulatorNameKey','String').SetString( 'Name');
 CL.AddConstantN('krsEmulatorWorkingFoldeKey','String').SetString( 'WorkingFolder');
 CL.AddConstantN('krsEmulatorParametersKey','String').SetString( 'Parameters');
 CL.AddConstantN('krsEmulatorExitCodeKey','String').SetString( 'ExitCode');
 CL.AddConstantN('krsEmulatorExeFileKey','String').SetString( 'ExeFile');
 CL.AddConstantN('krsEmulatorFileExtKey','String').SetString( 'Extensions');
 CL.AddConstantN('krsEmulatorDeveloperKey','String').SetString( 'Developer');
 CL.AddConstantN('krsEmulatorWebPageKey','String').SetString( 'WebPage');
 CL.AddConstantN('krsEmulatorIconKey','String').SetString( 'Icon');
 CL.AddConstantN('krsEmulatorImageKey','String').SetString( 'Image');
 CL.AddConstantN('krsEmulatorInfoFileKey','String').SetString( 'InfoFile');
 CL.AddConstantN('kEmutecaEmuDirKey','String').SetString( '%EMUDIR%');
 CL.AddConstantN('kEmutecaRomDirKey','String').SetString( '%ROMDIR%');
 CL.AddConstantN('kEmutecaCurrentDirKey','String').SetString( '%CURRENTDIR%');
 CL.AddConstantN('kEmutecaROMPathKey','String').SetString( '%ROM%');
 CL.AddConstantN('kEmutecaROMFileNameKey','String').SetString( '%ROMNAME%');
 CL.AddConstantN('kEmutecaROMFileNameNoExtKey','String').SetString( '%ROMNAMENOEXT%');
 CL.AddConstantN('kEmutecaROMFileExtKey','String').SetString( '%ROMEXT%');
  SIRegister_cEmutecaEmulator(CL);
  CL.AddTypeS('TEmutecaReturnEmulatorCB', 'Function ( aEmulator : cEmutecaEmula'
   +'tor) : boolean');
end;

(* === run-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure cEmutecaEmulatorStats_R(Self: cEmutecaEmulator; var T: cEmutecaPlayingStats);
begin T := Self.Stats; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaEmulatorInfoFile_W(Self: cEmutecaEmulator; const T: string);
begin Self.InfoFile := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaEmulatorInfoFile_R(Self: cEmutecaEmulator; var T: string);
begin T := Self.InfoFile; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaEmulatorImage_W(Self: cEmutecaEmulator; const T: string);
begin Self.Image := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaEmulatorImage_R(Self: cEmutecaEmulator; var T: string);
begin T := Self.Image; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaEmulatorIcon_W(Self: cEmutecaEmulator; const T: string);
begin Self.Icon := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaEmulatorIcon_R(Self: cEmutecaEmulator; var T: string);
begin T := Self.Icon; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaEmulatorWebPage_W(Self: cEmutecaEmulator; const T: string);
begin Self.WebPage := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaEmulatorWebPage_R(Self: cEmutecaEmulator; var T: string);
begin T := Self.WebPage; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaEmulatorDeveloper_W(Self: cEmutecaEmulator; const T: string);
begin Self.Developer := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaEmulatorDeveloper_R(Self: cEmutecaEmulator; var T: string);
begin T := Self.Developer; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaEmulatorExitCode_W(Self: cEmutecaEmulator; const T: integer);
begin Self.ExitCode := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaEmulatorExitCode_R(Self: cEmutecaEmulator; var T: integer);
begin T := Self.ExitCode; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaEmulatorFileExt_W(Self: cEmutecaEmulator; const T: TStringList);
begin Self.FileExt := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaEmulatorFileExt_R(Self: cEmutecaEmulator; var T: TStringList);
begin T := Self.FileExt; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaEmulatorParameters_W(Self: cEmutecaEmulator; const T: string);
begin Self.Parameters := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaEmulatorParameters_R(Self: cEmutecaEmulator; var T: string);
begin T := Self.Parameters; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaEmulatorWorkingFolder_W(Self: cEmutecaEmulator; const T: string);
begin Self.WorkingFolder := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaEmulatorWorkingFolder_R(Self: cEmutecaEmulator; var T: string);
begin T := Self.WorkingFolder; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaEmulatorExeFile_W(Self: cEmutecaEmulator; const T: string);
begin Self.ExeFile := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaEmulatorExeFile_R(Self: cEmutecaEmulator; var T: string);
begin T := Self.ExeFile; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaEmulatorEmulatorName_W(Self: cEmutecaEmulator; const T: string);
begin Self.EmulatorName := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaEmulatorEmulatorName_R(Self: cEmutecaEmulator; var T: string);
begin T := Self.EmulatorName; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaEmulatorEnabled_W(Self: cEmutecaEmulator; const T: boolean);
begin Self.Enabled := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaEmulatorEnabled_R(Self: cEmutecaEmulator; var T: boolean);
begin T := Self.Enabled; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaEmulatorID_W(Self: cEmutecaEmulator; const T: string);
begin Self.ID := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaEmulatorID_R(Self: cEmutecaEmulator; var T: string);
begin T := Self.ID; end;

(*----------------------------------------------------------------------------*)
procedure RIRegister_cEmutecaEmulator(CL: TPSRuntimeClassImporter);
begin
  with CL.Add(cEmutecaEmulator) do
  begin
    RegisterMethod(@cEmutecaEmulator.Execute, 'Execute');
    RegisterMethod(@cEmutecaEmulator.ExecuteAlone, 'ExecuteAlone');
    RegisterMethod(@cEmutecaEmulator.LoadFromIni, 'LoadFromIni');
    RegisterMethod(@cEmutecaEmulator.SaveToIni, 'SaveToIni');
    RegisterPropertyHelper(@cEmutecaEmulatorID_R,@cEmutecaEmulatorID_W,'ID');
    RegisterPropertyHelper(@cEmutecaEmulatorEnabled_R,@cEmutecaEmulatorEnabled_W,'Enabled');
    RegisterPropertyHelper(@cEmutecaEmulatorEmulatorName_R,@cEmutecaEmulatorEmulatorName_W,'EmulatorName');
    RegisterPropertyHelper(@cEmutecaEmulatorExeFile_R,@cEmutecaEmulatorExeFile_W,'ExeFile');
    RegisterPropertyHelper(@cEmutecaEmulatorWorkingFolder_R,@cEmutecaEmulatorWorkingFolder_W,'WorkingFolder');
    RegisterPropertyHelper(@cEmutecaEmulatorParameters_R,@cEmutecaEmulatorParameters_W,'Parameters');
    RegisterPropertyHelper(@cEmutecaEmulatorFileExt_R,@cEmutecaEmulatorFileExt_W,'FileExt');
    RegisterPropertyHelper(@cEmutecaEmulatorExitCode_R,@cEmutecaEmulatorExitCode_W,'ExitCode');
    RegisterPropertyHelper(@cEmutecaEmulatorDeveloper_R,@cEmutecaEmulatorDeveloper_W,'Developer');
    RegisterPropertyHelper(@cEmutecaEmulatorWebPage_R,@cEmutecaEmulatorWebPage_W,'WebPage');
    RegisterPropertyHelper(@cEmutecaEmulatorIcon_R,@cEmutecaEmulatorIcon_W,'Icon');
    RegisterPropertyHelper(@cEmutecaEmulatorImage_R,@cEmutecaEmulatorImage_W,'Image');
    RegisterPropertyHelper(@cEmutecaEmulatorInfoFile_R,@cEmutecaEmulatorInfoFile_W,'InfoFile');
    RegisterPropertyHelper(@cEmutecaEmulatorStats_R,nil,'Stats');
  end;
end;

(*----------------------------------------------------------------------------*)
procedure RIRegister_ucEmutecaEmulator(CL: TPSRuntimeClassImporter);
begin
  RIRegister_cEmutecaEmulator(CL);
end;

 
 
{ TPSImport_ucEmutecaEmulator }
(*----------------------------------------------------------------------------*)
procedure TPSImport_ucEmutecaEmulator.CompileImport1(CompExec: TPSScript);
begin
  SIRegister_ucEmutecaEmulator(CompExec.Comp);
end;
(*----------------------------------------------------------------------------*)
procedure TPSImport_ucEmutecaEmulator.ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter);
begin
  RIRegister_ucEmutecaEmulator(ri);
end;
(*----------------------------------------------------------------------------*)
 
 
end.
