unit uPSI_uGameStats;
{
This file has been generated by UnitParser v0.7, written by M. Knight
and updated by NP. v/d Spek and George Birbilis. 
Source Code from Carlo Kok has been used to implement various sections of
UnitParser. Components of ROPS are used in the construction of UnitParser,
code implementing the class wrapper is taken from Carlo Kok's conv utility

}
interface
 
uses
   SysUtils
  ,Classes
  ,uPSComponent
  ,uPSRuntime
  ,uPSCompiler
  ;
 
type 
(*----------------------------------------------------------------------------*)
  TPSImport_uGameStats = class(TPSPlugin)
  protected
    procedure CompileImport1(CompExec: TPSScript); override;
    procedure ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter); override;
  end;
 
 
{ compile-time registration functions }
procedure SIRegister_cGameStats(CL: TPSPascalCompiler);
procedure SIRegister_uGameStats(CL: TPSPascalCompiler);

{ run-time registration functions }
procedure RIRegister_cGameStats(CL: TPSRuntimeClassImporter);
procedure RIRegister_uGameStats(CL: TPSRuntimeClassImporter);

procedure Register;

implementation


uses
   dateutils
  ,uEmutecaStats
  ;
 
 
procedure Register;
begin
  RegisterComponents('Pascal Script', [TPSImport_uGameStats]);
end;

(* === compile-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure SIRegister_cGameStats(CL: TPSPascalCompiler);
begin
  //with RegClassS(CL,'TObject', 'cGameStats') do
  with CL.AddClassN(CL.FindClass('TObject'),'cGameStats') do
  begin
    RegisterProperty('LastTime', 'TDateTime', iptrw);
    RegisterProperty('TimesPlayed', 'LongWord', iptrw);
    RegisterProperty('PlayingTime', 'LongWord', iptrw);
    RegisterProperty('IconIndex', 'Integer', iptrw);
    RegisterMethod('Procedure IncTimesPlayed');
    RegisterMethod('Procedure AddPlayingTime( const Stop : TDateTime; Start : TDateTime)');
    RegisterMethod('Constructor Create');
  end;
end;

(*----------------------------------------------------------------------------*)
procedure SIRegister_uGameStats(CL: TPSPascalCompiler);
begin
  SIRegister_cGameStats(CL);
end;

(* === run-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure cGameStatsIconIndex_W(Self: cGameStats; const T: Integer);
begin Self.IconIndex := T; end;

(*----------------------------------------------------------------------------*)
procedure cGameStatsIconIndex_R(Self: cGameStats; var T: Integer);
begin T := Self.IconIndex; end;

(*----------------------------------------------------------------------------*)
procedure cGameStatsPlayingTime_W(Self: cGameStats; const T: LongWord);
begin Self.PlayingTime := T; end;

(*----------------------------------------------------------------------------*)
procedure cGameStatsPlayingTime_R(Self: cGameStats; var T: LongWord);
begin T := Self.PlayingTime; end;

(*----------------------------------------------------------------------------*)
procedure cGameStatsTimesPlayed_W(Self: cGameStats; const T: LongWord);
begin Self.TimesPlayed := T; end;

(*----------------------------------------------------------------------------*)
procedure cGameStatsTimesPlayed_R(Self: cGameStats; var T: LongWord);
begin T := Self.TimesPlayed; end;

(*----------------------------------------------------------------------------*)
procedure cGameStatsLastTime_W(Self: cGameStats; const T: TDateTime);
begin Self.LastTime := T; end;

(*----------------------------------------------------------------------------*)
procedure cGameStatsLastTime_R(Self: cGameStats; var T: TDateTime);
begin T := Self.LastTime; end;

(*----------------------------------------------------------------------------*)
procedure RIRegister_cGameStats(CL: TPSRuntimeClassImporter);
begin
  with CL.Add(cGameStats) do
  begin
    RegisterPropertyHelper(@cGameStatsLastTime_R,@cGameStatsLastTime_W,'LastTime');
    RegisterPropertyHelper(@cGameStatsTimesPlayed_R,@cGameStatsTimesPlayed_W,'TimesPlayed');
    RegisterPropertyHelper(@cGameStatsPlayingTime_R,@cGameStatsPlayingTime_W,'PlayingTime');
    RegisterPropertyHelper(@cGameStatsIconIndex_R,@cGameStatsIconIndex_W,'IconIndex');
    RegisterMethod(@cGameStats.IncTimesPlayed, 'IncTimesPlayed');
    RegisterMethod(@cGameStats.AddPlayingTime, 'AddPlayingTime');
    RegisterConstructor(@cGameStats.Create, 'Create');
  end;
end;

(*----------------------------------------------------------------------------*)
procedure RIRegister_uGameStats(CL: TPSRuntimeClassImporter);
begin
  RIRegister_cGameStats(CL);
end;

 
 
{ TPSImport_uGameStats }
(*----------------------------------------------------------------------------*)
procedure TPSImport_uGameStats.CompileImport1(CompExec: TPSScript);
begin
  SIRegister_uGameStats(CompExec.Comp);
end;
(*----------------------------------------------------------------------------*)
procedure TPSImport_uGameStats.ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter);
begin
  RIRegister_uGameStats(ri);
end;
(*----------------------------------------------------------------------------*)
 
 
end.
