unit uPSI_uEmutecaCommon;
{
This file has been generated by UnitParser v0.7, written by M. Knight
and updated by NP. v/d Spek and George Birbilis. 
Source Code from Carlo Kok has been used to implement various sections of
UnitParser. Components of ROPS are used in the construction of UnitParser,
code implementing the class wrapper is taken from Carlo Kok's conv utility

}
interface
 
uses
   SysUtils
  ,Classes
  ,uPSComponent
  ,uPSRuntime
  ,uPSCompiler
  ;
 
type 
(*----------------------------------------------------------------------------*)
  TPSImport_uEmutecaCommon = class(TPSPlugin)
  protected
    procedure CompileImport1(CompExec: TPSScript); override;
    procedure ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter); override;
  end;
 
 
{ compile-time registration functions }
procedure SIRegister_uEmutecaCommon(CL: TPSPascalCompiler);

{ run-time registration functions }

procedure Register;

implementation


uses
   uEmutecaCommon
  ;
 
 
procedure Register;
begin
  RegisterComponents('Pascal Script', [TPSImport_uEmutecaCommon]);
end;

(* === compile-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure SIRegister_uEmutecaCommon(CL: TPSPascalCompiler);
begin
 CL.AddConstantN('krsEmuteca','String').SetString( 'Emuteca');
 CL.AddConstantN('krsEmutecaGameSubFolder','String').SetString( 'Game/');
 CL.AddConstantN('kGroupSectionKey','String').SetString( 'Group: ');
 CL.AddConstantN('kEmutecaVirtualFolderExt','String').SetString( '.(folder)');
 CL.AddConstantN('kEmutecaVirtualGroupExt','String').SetString( '.(group)');
 CL.AddConstantN('kEmutecaVirtualGameExt','String').SetString( '.(game)');
 CL.AddConstantN('kEmutecaExecErrorNoGame','LongInt').SetInt( - 300);
 CL.AddConstantN('kEmutecaDecompressError','LongInt').SetInt( - 301);
 CL.AddConstantN('krsCRC32','String').SetString( 'CRC32');
 CL.AddConstantN('krsSHA1','String').SetString( 'SHA1');
 CL.AddConstantN('krsFileName','String').SetString( 'FileName');
 CL.AddConstantN('krsCustom','String').SetString( 'Custom');
 CL.AddConstantN('rsZones','String').SetString( 'Zones');
 CL.AddConstantN('rsDeveloper','String').SetString( 'Developer');
 CL.AddConstantN('rsPublisher','String').SetString( 'Publisher');
 CL.AddConstantN('rsVersion','String').SetString( 'Version');
 CL.AddConstantN('rsFilename','String').SetString( 'Filename');
 CL.AddConstantN('rsFmtNItems','String').SetString( '%0:d items. (%1:d visible)');
 CL.AddConstantN('rsFmtNTimes','String').SetString( '%0:d times.');
 CL.AddConstantN('rsNever','String').SetString( 'Never');
 CL.AddConstantN('rsUnknown','String').SetString( ' Unknown');
 CL.AddConstantN('rsFmtApplicationTitle','String').SetString( '%0:s %1:s');
 CL.AddConstantN('rsFmtWindowCaption','String').SetString( '%0:s : %1:s');
  CL.AddTypeS('TEmutecaProgressCallBack', 'Function ( const Title, Info1, Info2'
   +' : string; const Value, MaxValue : int64) : boolean');
end;

(* === run-time registration functions === *)
 
 
{ TPSImport_uEmutecaCommon }
(*----------------------------------------------------------------------------*)
procedure TPSImport_uEmutecaCommon.CompileImport1(CompExec: TPSScript);
begin
  SIRegister_uEmutecaCommon(CompExec.Comp);
end;
(*----------------------------------------------------------------------------*)
procedure TPSImport_uEmutecaCommon.ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter);
begin
  //RIRegister_uEmutecaCommon(ri);
end;
(*----------------------------------------------------------------------------*)
 
 
end.
