unit uPSI_ucEmutecaSoftware;
{
This file has been generated by UnitParser v0.7, written by M. Knight
and updated by NP. v/d Spek and George Birbilis. 
Source Code from Carlo Kok has been used to implement various sections of
UnitParser. Components of ROPS are used in the construction of UnitParser,
code implementing the class wrapper is taken from Carlo Kok's conv utility

}
interface
 
uses
   SysUtils
  ,Classes
  ,uPSComponent
  ,uPSRuntime
  ,uPSCompiler
  ;
 
type 
(*----------------------------------------------------------------------------*)
  TPSImport_ucEmutecaSoftware = class(TPSPlugin)
  protected
    procedure CompileImport1(CompExec: TPSScript); override;
    procedure ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter); override;
  end;
 
 
{ compile-time registration functions }
procedure SIRegister_cEmutecaSoftware(CL: TPSPascalCompiler);
procedure SIRegister_ucEmutecaSoftware(CL: TPSPascalCompiler);

{ run-time registration functions }
procedure RIRegister_cEmutecaSoftware(CL: TPSRuntimeClassImporter);
procedure RIRegister_ucEmutecaSoftware(CL: TPSRuntimeClassImporter);

procedure Register;

implementation


uses
   fgl
  ,LazFileUtils
  ,uCHXStrUtils
  ,ucEmutecaSoftware
  ;
 
 
procedure Register;
begin
  RegisterComponents('Pascal Script', [TPSImport_ucEmutecaSoftware]);
end;

(* === compile-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure SIRegister_cEmutecaSoftware(CL: TPSPascalCompiler);
begin
  //with RegClassS(CL,'caEmutecaStorableTxt', 'cEmutecaSoftware') do
  with CL.AddClassN(CL.FindClass('caEmutecaStorableTxt'),'cEmutecaSoftware') do
  begin
    RegisterProperty('DataString', 'string', iptrw);
    RegisterProperty('ID', 'string', iptrw);
    RegisterProperty('System', 'string', iptrw);
    RegisterProperty('Parent', 'string', iptrw);
    RegisterProperty('Title', 'string', iptrw);
    RegisterProperty('Description', 'string', iptrw);
    RegisterProperty('Folder', 'string', iptrw);
    RegisterProperty('FileName', 'string', iptrw);
  end;
end;

(*----------------------------------------------------------------------------*)
procedure SIRegister_ucEmutecaSoftware(CL: TPSPascalCompiler);
begin
  SIRegister_cEmutecaSoftware(CL);
end;

(* === run-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure cEmutecaSoftwareFileName_W(Self: cEmutecaSoftware; const T: string);
begin Self.FileName := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaSoftwareFileName_R(Self: cEmutecaSoftware; var T: string);
begin T := Self.FileName; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaSoftwareFolder_W(Self: cEmutecaSoftware; const T: string);
begin Self.Folder := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaSoftwareFolder_R(Self: cEmutecaSoftware; var T: string);
begin T := Self.Folder; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaSoftwareDescription_W(Self: cEmutecaSoftware; const T: string);
begin Self.Version := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaSoftwareDescription_R(Self: cEmutecaSoftware; var T: string);
begin T := Self.Version; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaSoftwareTitle_W(Self: cEmutecaSoftware; const T: string);
begin Self.Title := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaSoftwareTitle_R(Self: cEmutecaSoftware; var T: string);
begin T := Self.Title; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaSoftwareParent_W(Self: cEmutecaSoftware; const T: string);
begin Self.ParentKey := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaSoftwareParent_R(Self: cEmutecaSoftware; var T: string);
begin T := Self.ParentKey; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaSoftwareSystem_W(Self: cEmutecaSoftware; const T: string);
begin Self.SystemKey := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaSoftwareSystem_R(Self: cEmutecaSoftware; var T: string);
begin T := Self.SystemKey; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaSoftwareID_W(Self: cEmutecaSoftware; const T: string);
begin Self.ID := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaSoftwareID_R(Self: cEmutecaSoftware; var T: string);
begin T := Self.ID; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaSoftwareDataString_W(Self: cEmutecaSoftware; const T: string);
begin Self.DataString := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaSoftwareDataString_R(Self: cEmutecaSoftware; var T: string);
begin T := Self.DataString; end;

(*----------------------------------------------------------------------------*)
procedure RIRegister_cEmutecaSoftware(CL: TPSRuntimeClassImporter);
begin
  with CL.Add(cEmutecaSoftware) do
  begin
    RegisterPropertyHelper(@cEmutecaSoftwareDataString_R,@cEmutecaSoftwareDataString_W,'DataString');
    RegisterPropertyHelper(@cEmutecaSoftwareID_R,@cEmutecaSoftwareID_W,'ID');
    RegisterPropertyHelper(@cEmutecaSoftwareSystem_R,@cEmutecaSoftwareSystem_W,'System');
    RegisterPropertyHelper(@cEmutecaSoftwareParent_R,@cEmutecaSoftwareParent_W,'Parent');
    RegisterPropertyHelper(@cEmutecaSoftwareTitle_R,@cEmutecaSoftwareTitle_W,'Title');
    RegisterPropertyHelper(@cEmutecaSoftwareDescription_R,@cEmutecaSoftwareDescription_W,'Description');
    RegisterPropertyHelper(@cEmutecaSoftwareFolder_R,@cEmutecaSoftwareFolder_W,'Folder');
    RegisterPropertyHelper(@cEmutecaSoftwareFileName_R,@cEmutecaSoftwareFileName_W,'FileName');
  end;
end;

(*----------------------------------------------------------------------------*)
procedure RIRegister_ucEmutecaSoftware(CL: TPSRuntimeClassImporter);
begin
  RIRegister_cEmutecaSoftware(CL);
end;

 
 
{ TPSImport_ucEmutecaSoftware }
(*----------------------------------------------------------------------------*)
procedure TPSImport_ucEmutecaSoftware.CompileImport1(CompExec: TPSScript);
begin
  SIRegister_ucEmutecaSoftware(CompExec.Comp);
end;
(*----------------------------------------------------------------------------*)
procedure TPSImport_ucEmutecaSoftware.ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter);
begin
  RIRegister_ucEmutecaSoftware(ri);
end;
(*----------------------------------------------------------------------------*)
 
 
end.
