unit uPSI_ucEmutecaParent;
{
This file has been generated by UnitParser v0.7, written by M. Knight
and updated by NP. v/d Spek and George Birbilis. 
Source Code from Carlo Kok has been used to implement various sections of
UnitParser. Components of ROPS are used in the construction of UnitParser,
code implementing the class wrapper is taken from Carlo Kok's conv utility

}
interface
 
uses
   SysUtils
  ,Classes
  ,uPSComponent
  ,uPSRuntime
  ,uPSCompiler
  ;
 
type 
(*----------------------------------------------------------------------------*)
  TPSImport_ucEmutecaParent = class(TPSPlugin)
  protected
    procedure CompileImport1(CompExec: TPSScript); override;
    procedure ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter); override;
  end;
 
 
{ compile-time registration functions }
procedure SIRegister_cEmutecaParent(CL: TPSPascalCompiler);
procedure SIRegister_ucEmutecaParent(CL: TPSPascalCompiler);

{ run-time registration functions }
procedure RIRegister_cEmutecaParent(CL: TPSRuntimeClassImporter);
procedure RIRegister_ucEmutecaParent(CL: TPSRuntimeClassImporter);

procedure Register;

implementation


uses
   fgl
  ,LazFileUtils
  ,uCHXStrUtils
  ,uaEmutecaStorable
  ,ucEmutecaParent
  ;
 
 
procedure Register;
begin
  RegisterComponents('Pascal Script', [TPSImport_ucEmutecaParent]);
end;

(* === compile-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure SIRegister_cEmutecaParent(CL: TPSPascalCompiler);
begin
  //with RegClassS(CL,'caEmutecaStorableTxt', 'cEmutecaParent') do
  with CL.AddClassN(CL.FindClass('caEmutecaStorableTxt'),'cEmutecaParent') do
  begin
    RegisterProperty('DataString', 'string', iptrw);
    RegisterProperty('Title', 'string', iptrw);
    RegisterProperty('System', 'string', iptrw);
    RegisterProperty('ID', 'string', iptrw);
  end;
end;

(*----------------------------------------------------------------------------*)
procedure SIRegister_ucEmutecaParent(CL: TPSPascalCompiler);
begin
  SIRegister_cEmutecaParent(CL);
end;

(* === run-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure cEmutecaParentID_W(Self: cEmutecaParent; const T: string);
begin Self.ID := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaParentID_R(Self: cEmutecaParent; var T: string);
begin T := Self.ID; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaParentSystem_W(Self: cEmutecaParent; const T: string);
begin Self.System := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaParentSystem_R(Self: cEmutecaParent; var T: string);
begin T := Self.System; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaParentTitle_W(Self: cEmutecaParent; const T: string);
begin Self.Title := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaParentTitle_R(Self: cEmutecaParent; var T: string);
begin T := Self.Title; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaParentDataString_W(Self: cEmutecaParent; const T: string);
begin Self.DataString := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaParentDataString_R(Self: cEmutecaParent; var T: string);
begin T := Self.DataString; end;

(*----------------------------------------------------------------------------*)
procedure RIRegister_cEmutecaParent(CL: TPSRuntimeClassImporter);
begin
  with CL.Add(cEmutecaParent) do
  begin
    RegisterPropertyHelper(@cEmutecaParentDataString_R,@cEmutecaParentDataString_W,'DataString');
    RegisterPropertyHelper(@cEmutecaParentTitle_R,@cEmutecaParentTitle_W,'Title');
    RegisterPropertyHelper(@cEmutecaParentSystem_R,@cEmutecaParentSystem_W,'System');
    RegisterPropertyHelper(@cEmutecaParentID_R,@cEmutecaParentID_W,'ID');
  end;
end;

(*----------------------------------------------------------------------------*)
procedure RIRegister_ucEmutecaParent(CL: TPSRuntimeClassImporter);
begin
  RIRegister_cEmutecaParent(CL);
end;

 
 
{ TPSImport_ucEmutecaParent }
(*----------------------------------------------------------------------------*)
procedure TPSImport_ucEmutecaParent.CompileImport1(CompExec: TPSScript);
begin
  SIRegister_ucEmutecaParent(CompExec.Comp);
end;
(*----------------------------------------------------------------------------*)
procedure TPSImport_ucEmutecaParent.ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter);
begin
  RIRegister_ucEmutecaParent(ri);
end;
(*----------------------------------------------------------------------------*)
 
 
end.
