unit uPSI_ucEmutecaEmulatorManager;
{
This file has been generated by UnitParser v0.7, written by M. Knight
and updated by NP. v/d Spek and George Birbilis. 
Source Code from Carlo Kok has been used to implement various sections of
UnitParser. Components of ROPS are used in the construction of UnitParser,
code implementing the class wrapper is taken from Carlo Kok's conv utility

}
interface
 
uses
   SysUtils
  ,Classes
  ,uPSComponent
  ,uPSRuntime
  ,uPSCompiler
  ;
 
type 
(*----------------------------------------------------------------------------*)
  TPSImport_ucEmutecaEmulatorManager = class(TPSPlugin)
  protected
    procedure CompileImport1(CompExec: TPSScript); override;
    procedure ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter); override;
  end;
 
 
{ compile-time registration functions }
procedure SIRegister_cEmutecaEmulatorManager(CL: TPSPascalCompiler);
procedure SIRegister_ucEmutecaEmulatorManager(CL: TPSPascalCompiler);

{ run-time registration functions }
procedure RIRegister_cEmutecaEmulatorManager(CL: TPSRuntimeClassImporter);
procedure RIRegister_ucEmutecaEmulatorManager(CL: TPSRuntimeClassImporter);

procedure Register;

implementation


uses
   LazFileUtils
  ,LazUTF8
  ,IniFiles
  ,ucEmutecaEmulator
  ,uaEmutecaManager
  ,ucEmutecaEmulatorManager
  ;
 
 
procedure Register;
begin
  RegisterComponents('Pascal Script', [TPSImport_ucEmutecaEmulatorManager]);
end;

(* === compile-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure SIRegister_cEmutecaEmulatorManager(CL: TPSPascalCompiler);
begin
  //with RegClassS(CL,'caEmutecaManagerIni', 'cEmutecaEmulatorManager') do
  with CL.AddClassN(CL.FindClass('caEmutecaManagerIni'),'cEmutecaEmulatorManager') do
  begin
    RegisterProperty('FullList', 'cEmutecaEmulatorList', iptr);
    RegisterMethod('Function ItemById( aId : string) : cEmutecaEmulator');
    RegisterMethod('Function RunEmulator( const EmulatorID, GameFile : string) : longword');
  end;
end;

(*----------------------------------------------------------------------------*)
procedure SIRegister_ucEmutecaEmulatorManager(CL: TPSPascalCompiler);
begin
  SIRegister_cEmutecaEmulatorManager(CL);
end;

(* === run-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure cEmutecaEmulatorManagerFullList_R(Self: cEmutecaEmulatorManager; var T: cEmutecaEmulatorList);
begin T := Self.FullList; end;

(*----------------------------------------------------------------------------*)
procedure RIRegister_cEmutecaEmulatorManager(CL: TPSRuntimeClassImporter);
begin
  with CL.Add(cEmutecaEmulatorManager) do
  begin
    RegisterPropertyHelper(@cEmutecaEmulatorManagerFullList_R,nil,'FullList');
    RegisterMethod(@cEmutecaEmulatorManager.ItemById, 'ItemById');
    RegisterMethod(@cEmutecaEmulatorManager.RunEmulator, 'RunEmulator');
  end;
end;

(*----------------------------------------------------------------------------*)
procedure RIRegister_ucEmutecaEmulatorManager(CL: TPSRuntimeClassImporter);
begin
  RIRegister_cEmutecaEmulatorManager(CL);
end;

 
 
{ TPSImport_ucEmutecaEmulatorManager }
(*----------------------------------------------------------------------------*)
procedure TPSImport_ucEmutecaEmulatorManager.CompileImport1(CompExec: TPSScript);
begin
  SIRegister_ucEmutecaEmulatorManager(CompExec.Comp);
end;
(*----------------------------------------------------------------------------*)
procedure TPSImport_ucEmutecaEmulatorManager.ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter);
begin
  RIRegister_ucEmutecaEmulatorManager(ri);
end;
(*----------------------------------------------------------------------------*)
 
 
end.
