unit uPSI_uaCHXStorable;
{
This file has been generated by UnitParser v0.7, written by M. Knight
and updated by NP. v/d Spek and George Birbilis. 
Source Code from Carlo Kok has been used to implement various sections of
UnitParser. Components of ROPS are used in the construction of UnitParser,
code implementing the class wrapper is taken from Carlo Kok's conv utility

}
interface
 
uses
   SysUtils
  ,Classes
  ,uPSComponent
  ,uPSRuntime
  ,uPSCompiler
  ;
 
type 
(*----------------------------------------------------------------------------*)
  TPSImport_uaCHXStorable = class(TPSPlugin)
  protected
    procedure CompileImport1(CompExec: TPSScript); override;
    procedure ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter); override;
  end;
 
 
{ compile-time registration functions }
procedure SIRegister_caCHXStorable(CL: TPSPascalCompiler);
procedure SIRegister_uaCHXStorable(CL: TPSPascalCompiler);

{ run-time registration functions }
procedure RIRegister_caCHXStorable(CL: TPSRuntimeClassImporter);
procedure RIRegister_uaCHXStorable(CL: TPSRuntimeClassImporter);

procedure Register;

implementation


uses
   IniFiles
  ,LazUTF8
  ,LazFileUtils
  ,uaCHXStorable
  ;
 
 
procedure Register;
begin
  RegisterComponents('Pascal Script', [TPSImport_uaCHXStorable]);
end;

(* === compile-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure SIRegister_caCHXStorable(CL: TPSPascalCompiler);
begin
  //with RegClassS(CL,'TComponent', 'caCHXStorable') do
  with CL.AddClassN(CL.FindClass('TComponent'),'caCHXStorable') do
  begin
    RegisterMethod('Procedure LoadFromFileIni( Filename : TFilename)');
    RegisterMethod('Procedure LoadFromIni( aIniFile : TCustomIniFile)');
    RegisterMethod('Procedure LoadFromFileTxt( Filename : TFilename)');
    RegisterMethod('Procedure LoadFromStrLst( aTxtFile : TStrings)');
    RegisterMethod('Procedure SaveToFileIni( Filename : TFilename; const ExportMode : boolean)');
    RegisterMethod('Procedure SaveToIni( IniFile : TCustomIniFile; const ExportMode : boolean)');
    RegisterMethod('Procedure SaveToFileTxt( Filename : TFilename; const ExportMode : boolean)');
    RegisterMethod('Procedure SaveToStrLst( TxtFile : TStrings; const ExportMode : boolean)');
    RegisterProperty('DataFile', 'TFilename', iptrw);
  end;
end;

(*----------------------------------------------------------------------------*)
procedure SIRegister_uaCHXStorable(CL: TPSPascalCompiler);
begin
  SIRegister_caCHXStorable(CL);
end;

(* === run-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure caCHXStorableDataFile_W(Self: caCHXStorable; const T: TFilename);
begin Self.DataFile := T; end;

(*----------------------------------------------------------------------------*)
procedure caCHXStorableDataFile_R(Self: caCHXStorable; var T: TFilename);
begin T := Self.DataFile; end;

(*----------------------------------------------------------------------------*)
procedure RIRegister_caCHXStorable(CL: TPSRuntimeClassImporter);
begin
  with CL.Add(caCHXStorable) do
  begin
    RegisterVirtualMethod(@caCHXStorable.LoadFromFileIni, 'LoadFromFileIni');
    RegisterVirtualAbstractMethod(caCHXStorable, nil, 'LoadFromIni');
    RegisterVirtualMethod(@caCHXStorable.LoadFromFileTxt, 'LoadFromFileTxt');
    RegisterVirtualAbstractMethod(caCHXStorable, nil, 'LoadFromStrLst');
    RegisterVirtualMethod(@caCHXStorable.SaveToFileIni, 'SaveToFileIni');
    RegisterVirtualAbstractMethod(caCHXStorable, nil, 'SaveToIni');
    RegisterVirtualMethod(@caCHXStorable.SaveToFileTxt, 'SaveToFileTxt');
    RegisterVirtualAbstractMethod(caCHXStorable, nil, 'SaveToStrLst');
    RegisterPropertyHelper(@caCHXStorableDataFile_R,@caCHXStorableDataFile_W,'DataFile');
  end;
end;

(*----------------------------------------------------------------------------*)
procedure RIRegister_uaCHXStorable(CL: TPSRuntimeClassImporter);
begin
  RIRegister_caCHXStorable(CL);
end;

 
 
{ TPSImport_uaCHXStorable }
(*----------------------------------------------------------------------------*)
procedure TPSImport_uaCHXStorable.CompileImport1(CompExec: TPSScript);
begin
  SIRegister_uaCHXStorable(CompExec.Comp);
end;
(*----------------------------------------------------------------------------*)
procedure TPSImport_uaCHXStorable.ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter);
begin
  RIRegister_uaCHXStorable(ri);
end;
(*----------------------------------------------------------------------------*)
 
 
end.
