unit uPSI_ucEmutecaSystemManager;
{
This file has been generated by UnitParser v0.7, written by M. Knight
and updated by NP. v/d Spek and George Birbilis. 
Source Code from Carlo Kok has been used to implement various sections of
UnitParser. Components of ROPS are used in the construction of UnitParser,
code implementing the class wrapper is taken from Carlo Kok's conv utility

}
interface
 
uses
   SysUtils
  ,Classes
  ,uPSComponent
  ,uPSRuntime
  ,uPSCompiler
  ;
 
type 
(*----------------------------------------------------------------------------*)
  TPSImport_ucEmutecaSystemManager = class(TPSPlugin)
  protected
    procedure CompileImport1(CompExec: TPSScript); override;
    procedure ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter); override;
  end;
 
 
{ compile-time registration functions }
procedure SIRegister_cEmutecaSystemManager(CL: TPSPascalCompiler);
procedure SIRegister_ucEmutecaSystemManager(CL: TPSPascalCompiler);

{ run-time registration functions }
procedure RIRegister_cEmutecaSystemManager(CL: TPSRuntimeClassImporter);
procedure RIRegister_ucEmutecaSystemManager(CL: TPSRuntimeClassImporter);

procedure Register;

implementation


uses
   LazFileUtils
  ,LazUTF8
  ,IniFiles
  ,contnrs
  ,uaEmutecaManager
  ,ucEmutecaSystem
  ,ucEmutecaSystemManager
  ;
 
 
procedure Register;
begin
  RegisterComponents('Pascal Script', [TPSImport_ucEmutecaSystemManager]);
end;

(* === compile-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure SIRegister_cEmutecaSystemManager(CL: TPSPascalCompiler);
begin
  //with RegClassS(CL,'caEmutecaManager', 'cEmutecaSystemManager') do
  with CL.AddClassN(CL.FindClass('caEmutecaManager'),'cEmutecaSystemManager') do
  begin
    RegisterMethod('Function ItemById( aId : string; Autocreate : Boolean) : cEmutecaSystem');
    RegisterProperty('FullList', 'cEmutecaSystemList', iptr);
    RegisterProperty('VisibleList', 'cEmutecaSystemList', iptr);
  end;
end;

(*----------------------------------------------------------------------------*)
procedure SIRegister_ucEmutecaSystemManager(CL: TPSPascalCompiler);
begin
  SIRegister_cEmutecaSystemManager(CL);
end;

(* === run-time registration functions === *)
(*----------------------------------------------------------------------------*)

(*----------------------------------------------------------------------------*)
procedure cEmutecaSystemManagerFullList_R(Self: cEmutecaSystemManager; var T: cEmutecaSystemList);
begin T := Self.FullList; end;

(*----------------------------------------------------------------------------*)
procedure RIRegister_cEmutecaSystemManager(CL: TPSRuntimeClassImporter);
begin
  with CL.Add(cEmutecaSystemManager) do
  begin
    RegisterMethod(@cEmutecaSystemManager.ItemById, 'ItemById');
    RegisterPropertyHelper(@cEmutecaSystemManagerFullList_R,nil,'FullList');
  end;
end;

(*----------------------------------------------------------------------------*)
procedure RIRegister_ucEmutecaSystemManager(CL: TPSRuntimeClassImporter);
begin
  RIRegister_cEmutecaSystemManager(CL);
end;

 
 
{ TPSImport_ucEmutecaSystemManager }
(*----------------------------------------------------------------------------*)
procedure TPSImport_ucEmutecaSystemManager.CompileImport1(CompExec: TPSScript);
begin
  SIRegister_ucEmutecaSystemManager(CompExec.Comp);
end;
(*----------------------------------------------------------------------------*)
procedure TPSImport_ucEmutecaSystemManager.ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter);
begin
  RIRegister_ucEmutecaSystemManager(ri);
end;
(*----------------------------------------------------------------------------*)
 
 
end.
