unit uPSI_ucEmutecaParentManager;
{
This file has been generated by UnitParser v0.7, written by M. Knight
and updated by NP. v/d Spek and George Birbilis. 
Source Code from Carlo Kok has been used to implement various sections of
UnitParser. Components of ROPS are used in the construction of UnitParser,
code implementing the class wrapper is taken from Carlo Kok's conv utility

}
interface
 
uses
   SysUtils
  ,Classes
  ,uPSComponent
  ,uPSRuntime
  ,uPSCompiler
  ;
 
type 
(*----------------------------------------------------------------------------*)
  TPSImport_ucEmutecaParentManager = class(TPSPlugin)
  protected
    procedure CompileImport1(CompExec: TPSScript); override;
    procedure ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter); override;
  end;
 
 
{ compile-time registration functions }
procedure SIRegister_cEmutecaParentManager(CL: TPSPascalCompiler);
procedure SIRegister_ucEmutecaParentManager(CL: TPSPascalCompiler);

{ run-time registration functions }
procedure RIRegister_cEmutecaParentManager(CL: TPSRuntimeClassImporter);
procedure RIRegister_ucEmutecaParentManager(CL: TPSRuntimeClassImporter);

procedure Register;

implementation


uses
   FileUtil
  ,LazFileUtils
  ,LazUTF8
  ,LConvEncoding
  ,LResources
  ,uaEmutecaManager
  ,ucEmutecaParent
  ,u7zWrapper
  ,ucEmutecaParentManager
  ;
 
 
procedure Register;
begin
  RegisterComponents('Pascal Script', [TPSImport_ucEmutecaParentManager]);
end;

(* === compile-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure SIRegister_cEmutecaParentManager(CL: TPSPascalCompiler);
begin
  //with RegClassS(CL,'caEmutecaManagerTxt', 'cEmutecaParentManager') do
  with CL.AddClassN(CL.FindClass('caEmutecaManagerTxt'),'cEmutecaParentManager') do
  begin
    RegisterProperty('FullList', 'cEmutecaParentList', iptr);
    RegisterMethod('Function ItemById( aId : string) : cEmutecaParent');
  end;
end;

(*----------------------------------------------------------------------------*)
procedure SIRegister_ucEmutecaParentManager(CL: TPSPascalCompiler);
begin
  SIRegister_cEmutecaParentManager(CL);
end;

(* === run-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure cEmutecaParentManagerFullList_R(Self: cEmutecaParentManager; var T: cEmutecaParentList);
begin T := Self.FullList; end;

(*----------------------------------------------------------------------------*)
procedure RIRegister_cEmutecaParentManager(CL: TPSRuntimeClassImporter);
begin
  with CL.Add(cEmutecaParentManager) do
  begin
    RegisterPropertyHelper(@cEmutecaParentManagerFullList_R,nil,'FullList');
    RegisterMethod(@cEmutecaParentManager.ItemById, 'ItemById');
  end;
end;

(*----------------------------------------------------------------------------*)
procedure RIRegister_ucEmutecaParentManager(CL: TPSRuntimeClassImporter);
begin
  RIRegister_cEmutecaParentManager(CL);
end;

 
 
{ TPSImport_ucEmutecaParentManager }
(*----------------------------------------------------------------------------*)
procedure TPSImport_ucEmutecaParentManager.CompileImport1(CompExec: TPSScript);
begin
  SIRegister_ucEmutecaParentManager(CompExec.Comp);
end;
(*----------------------------------------------------------------------------*)
procedure TPSImport_ucEmutecaParentManager.ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter);
begin
  RIRegister_ucEmutecaParentManager(ri);
end;
(*----------------------------------------------------------------------------*)
 
 
end.
