unit uPSI_ucEmutecaSoftware;
{
This file has been generated by UnitParser v0.7, written by M. Knight
and updated by NP. v/d Spek and George Birbilis. 
Source Code from Carlo Kok has been used to implement various sections of
UnitParser. Components of ROPS are used in the construction of UnitParser,
code implementing the class wrapper is taken from Carlo Kok's conv utility

}
interface
 
uses
   SysUtils
  ,Classes
  ,uPSComponent
  ,uPSRuntime
  ,uPSCompiler
  ;
 
type 
(*----------------------------------------------------------------------------*)
  TPSImport_ucEmutecaSoftware = class(TPSPlugin)
  protected
    procedure CompileImport1(CompExec: TPSScript); override;
    procedure ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter); override;
  end;
 
 
{ compile-time registration functions }
procedure SIRegister_cEmutecaVersion(CL: TPSPascalCompiler);
procedure SIRegister_ucEmutecaSoftware(CL: TPSPascalCompiler);

{ run-time registration functions }
procedure RIRegister_cEmutecaVersion(CL: TPSRuntimeClassImporter);
procedure RIRegister_ucEmutecaSoftware(CL: TPSRuntimeClassImporter);

procedure Register;

implementation


uses
   fgl
  ,LazFileUtils
  ,uaEmutecaStorable
  ,uCHXStrUtils
  ,ucEmutecaSoftware
  ;
 
 
procedure Register;
begin
  RegisterComponents('Pascal Script', [TPSImport_ucEmutecaSoftware]);
end;

(* === compile-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure SIRegister_cEmutecaVersion(CL: TPSPascalCompiler);
begin
  //with RegClassS(CL,'caEmutecaStorableTxt', 'cEmutecaVersion') do
  with CL.AddClassN(CL.FindClass('caEmutecaStorableTxt'),'cEmutecaVersion') do
  begin
    RegisterProperty('DataString', 'string', iptrw);
    RegisterProperty('ID', 'string', iptrw);
    RegisterProperty('System', 'string', iptrw);
    RegisterProperty('Parent', 'string', iptrw);
    RegisterProperty('Title', 'string', iptrw);
    RegisterProperty('Description', 'string', iptrw);
    RegisterProperty('Folder', 'string', iptrw);
    RegisterProperty('FileName', 'string', iptrw);
  end;
end;

(*----------------------------------------------------------------------------*)
procedure SIRegister_ucEmutecaSoftware(CL: TPSPascalCompiler);
begin
  SIRegister_cEmutecaVersion(CL);
end;

(* === run-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure cEmutecaVersionFileName_W(Self: cEmutecaSoftware; const T: string);
begin Self.FileName := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaVersionFileName_R(Self: cEmutecaSoftware; var T: string);
begin T := Self.FileName; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaVersionFolder_W(Self: cEmutecaSoftware; const T: string);
begin Self.Folder := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaVersionFolder_R(Self: cEmutecaSoftware; var T: string);
begin T := Self.Folder; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaVersionDescription_W(Self: cEmutecaSoftware; const T: string);
begin Self.Description := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaVersionDescription_R(Self: cEmutecaSoftware; var T: string);
begin T := Self.Description; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaVersionTitle_W(Self: cEmutecaSoftware; const T: string);
begin Self.Title := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaVersionTitle_R(Self: cEmutecaSoftware; var T: string);
begin T := Self.Title; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaVersionParent_W(Self: cEmutecaSoftware; const T: string);
begin Self.Parent := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaVersionParent_R(Self: cEmutecaSoftware; var T: string);
begin T := Self.Parent; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaVersionSystem_W(Self: cEmutecaSoftware; const T: string);
begin Self.System := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaVersionSystem_R(Self: cEmutecaSoftware; var T: string);
begin T := Self.System; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaVersionID_W(Self: cEmutecaSoftware; const T: string);
begin Self.ID := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaVersionID_R(Self: cEmutecaSoftware; var T: string);
begin T := Self.ID; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaVersionDataString_W(Self: cEmutecaSoftware; const T: string);
begin Self.DataString := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaVersionDataString_R(Self: cEmutecaSoftware; var T: string);
begin T := Self.DataString; end;

(*----------------------------------------------------------------------------*)
procedure RIRegister_cEmutecaVersion(CL: TPSRuntimeClassImporter);
begin
  with CL.Add(cEmutecaSoftware) do
  begin
    RegisterPropertyHelper(@cEmutecaVersionDataString_R,@cEmutecaVersionDataString_W,'DataString');
    RegisterPropertyHelper(@cEmutecaVersionID_R,@cEmutecaVersionID_W,'ID');
    RegisterPropertyHelper(@cEmutecaVersionSystem_R,@cEmutecaVersionSystem_W,'System');
    RegisterPropertyHelper(@cEmutecaVersionParent_R,@cEmutecaVersionParent_W,'Parent');
    RegisterPropertyHelper(@cEmutecaVersionTitle_R,@cEmutecaVersionTitle_W,'Title');
    RegisterPropertyHelper(@cEmutecaVersionDescription_R,@cEmutecaVersionDescription_W,'Description');
    RegisterPropertyHelper(@cEmutecaVersionFolder_R,@cEmutecaVersionFolder_W,'Folder');
    RegisterPropertyHelper(@cEmutecaVersionFileName_R,@cEmutecaVersionFileName_W,'FileName');
  end;
end;

(*----------------------------------------------------------------------------*)
procedure RIRegister_ucEmutecaSoftware(CL: TPSRuntimeClassImporter);
begin
  RIRegister_cEmutecaVersion(CL);
end;

 
 
{ TPSImport_ucEmutecaSoftware }
(*----------------------------------------------------------------------------*)
procedure TPSImport_ucEmutecaSoftware.CompileImport1(CompExec: TPSScript);
begin
  SIRegister_ucEmutecaSoftware(CompExec.Comp);
end;
(*----------------------------------------------------------------------------*)
procedure TPSImport_ucEmutecaSoftware.ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter);
begin
  RIRegister_ucEmutecaSoftware(ri);
end;
(*----------------------------------------------------------------------------*)
 
 
end.
