unit uPSI_uaCHXConfig;
{
This file has been generated by UnitParser v0.7, written by M. Knight
and updated by NP. v/d Spek and George Birbilis. 
Source Code from Carlo Kok has been used to implement various sections of
UnitParser. Components of ROPS are used in the construction of UnitParser,
code implementing the class wrapper is taken from Carlo Kok's conv utility

}
interface
 
uses
   SysUtils
  ,Classes
  ,uPSComponent
  ,uPSRuntime
  ,uPSCompiler
  ;
 
type 
(*----------------------------------------------------------------------------*)
  TPSImport_uaCHXConfig = class(TPSPlugin)
  protected
    procedure CompileImport1(CompExec: TPSScript); override;
    procedure ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter); override;
  end;
 
 
{ compile-time registration functions }
procedure SIRegister_caCHXConfig(CL: TPSPascalCompiler);
procedure SIRegister_uaCHXConfig(CL: TPSPascalCompiler);

{ run-time registration functions }
procedure RIRegister_caCHXConfig(CL: TPSRuntimeClassImporter);
procedure RIRegister_uaCHXConfig(CL: TPSRuntimeClassImporter);

procedure Register;

implementation


uses
   IniFiles
  ,LazUTF8
  ,uCHXRscStr
  ,uCHXStrUtils
  ,uaCHXConfig
  ;
 
 
procedure Register;
begin
  RegisterComponents('Pascal Script', [TPSImport_uaCHXConfig]);
end;

(* === compile-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure SIRegister_caCHXConfig(CL: TPSPascalCompiler);
begin
  //with RegClassS(CL,'TComponent', 'caCHXConfig') do
  with CL.AddClassN(CL.FindClass('TComponent'),'caCHXConfig') do
  begin
    RegisterMethod('Procedure LoadConfig( aFileName : string)');
    RegisterMethod('Procedure SaveConfig( aFilename : string)');
    RegisterMethod('Procedure ResetDefaultConfig');
    RegisterProperty('ConfigFile', 'string', iptrw);
  end;
end;

(*----------------------------------------------------------------------------*)
procedure SIRegister_uaCHXConfig(CL: TPSPascalCompiler);
begin
  SIRegister_caCHXConfig(CL);
end;

(* === run-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure caCHXConfigConfigFile_W(Self: caCHXConfig; const T: string);
begin Self.ConfigFile := T; end;

(*----------------------------------------------------------------------------*)
procedure caCHXConfigConfigFile_R(Self: caCHXConfig; var T: string);
begin T := Self.ConfigFile; end;

(*----------------------------------------------------------------------------*)
procedure RIRegister_caCHXConfig(CL: TPSRuntimeClassImporter);
begin
  with CL.Add(caCHXConfig) do
  begin
    RegisterMethod(@caCHXConfig.LoadConfig, 'LoadConfig');
    RegisterMethod(@caCHXConfig.SaveConfig, 'SaveConfig');
    RegisterVirtualAbstractMethod(@caCHXConfig, @!.ResetDefaultConfig, 'ResetDefaultConfig');
    RegisterPropertyHelper(@caCHXConfigConfigFile_R,@caCHXConfigConfigFile_W,'ConfigFile');
  end;
end;

(*----------------------------------------------------------------------------*)
procedure RIRegister_uaCHXConfig(CL: TPSRuntimeClassImporter);
begin
  RIRegister_caCHXConfig(CL);
end;

 
 
{ TPSImport_uaCHXConfig }
(*----------------------------------------------------------------------------*)
procedure TPSImport_uaCHXConfig.CompileImport1(CompExec: TPSScript);
begin
  SIRegister_uaCHXConfig(CompExec.Comp);
end;
(*----------------------------------------------------------------------------*)
procedure TPSImport_uaCHXConfig.ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter);
begin
  RIRegister_uaCHXConfig(ri);
end;
(*----------------------------------------------------------------------------*)
 
 
end.
