unit uPSI_ucEmutecaConfig;
{
This file has been generated by UnitParser v0.7, written by M. Knight
and updated by NP. v/d Spek and George Birbilis. 
Source Code from Carlo Kok has been used to implement various sections of
UnitParser. Components of ROPS are used in the construction of UnitParser,
code implementing the class wrapper is taken from Carlo Kok's conv utility

}
interface
 
uses
   SysUtils
  ,Classes
  ,uPSComponent
  ,uPSRuntime
  ,uPSCompiler
  ;
 
type 
(*----------------------------------------------------------------------------*)
  TPSImport_ucEmutecaConfig = class(TPSPlugin)
  protected
    procedure CompileImport1(CompExec: TPSScript); override;
    procedure ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter); override;
  end;
 
 
{ compile-time registration functions }
procedure SIRegister_cEmutecaConfig(CL: TPSPascalCompiler);
procedure SIRegister_ucEmutecaConfig(CL: TPSPascalCompiler);

{ run-time registration functions }
procedure RIRegister_cEmutecaConfig(CL: TPSRuntimeClassImporter);
procedure RIRegister_ucEmutecaConfig(CL: TPSRuntimeClassImporter);

procedure Register;

implementation


uses
   LazFileUtils
  ,LazUTF8
  ,uCHXStrUtils
  ,uCHXRscStr
  ,u7zWrapper
  ,ucEmutecaConfig
  ;
 
 
procedure Register;
begin
  RegisterComponents('Pascal Script', [TPSImport_ucEmutecaConfig]);
end;

(* === compile-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure SIRegister_cEmutecaConfig(CL: TPSPascalCompiler);
begin
  //with RegClassS(CL,'TComponent', 'cEmutecaConfig') do
  with CL.AddClassN(CL.FindClass('TComponent'),'cEmutecaConfig') do
  begin
    RegisterProperty('ImagesFolder', 'string', iptrw);
    RegisterProperty('DefaultImagesSubfolder', 'string', iptrw);
    RegisterProperty('DefaultSystemImage', 'string', iptrw);
    RegisterProperty('DefaultSystemIcon', 'string', iptrw);
    RegisterProperty('DefaultEmulatorImage', 'string', iptrw);
    RegisterProperty('DefaultEmulatorIcon', 'string', iptrw);
    RegisterProperty('DefaultGameImage', 'string', iptrw);
    RegisterProperty('DefaultGameIcon', 'string', iptrw);
    RegisterProperty('ToolsFolder', 'string', iptrw);
    RegisterProperty('z7Subfolder', 'string', iptrw);
    RegisterProperty('z7CMExecutable', 'string', iptrw);
    RegisterProperty('z7GExecutable', 'string', iptrw);
    RegisterProperty('CommonMediaFolder', 'string', iptrw);
    RegisterProperty('CompanySubFolder', 'string', iptrw);
    RegisterProperty('YearSubFolder', 'string', iptrw);
    RegisterProperty('TagSubFolder', 'string', iptrw);
    RegisterProperty('EmulatorSubFolder', 'string', iptrw);
    RegisterProperty('ScriptsFolder', 'string', iptrw);
    RegisterProperty('GeneralScriptsSubFolder', 'string', iptrw);
    RegisterProperty('GameScriptsSubFolder', 'string', iptrw);
    RegisterProperty('GroupScriptsSubFolder', 'string', iptrw);
    RegisterProperty('DataFolder', 'string', iptrw);
    RegisterProperty('ParentsFile', 'string', iptrw);
    RegisterProperty('VersionsFile', 'string', iptrw);
    RegisterProperty('EmulatorsFile', 'string', iptrw);
    RegisterProperty('SystemsFile', 'string', iptrw);
    RegisterProperty('SysSubfolder', 'string', iptrw);
    RegisterProperty('SysStructFile', 'string', iptrw);
    RegisterProperty('GameDataExt', 'string', iptrw);
    RegisterProperty('GameGroupExt', 'string', iptrw);
    RegisterProperty('CompressedExtensions', 'TStringList', iptr);
    RegisterProperty('TextExtensions', 'TStringList', iptr);
    RegisterProperty('ImageExtensions', 'TStringList', iptr);
    RegisterProperty('MusicExtensions', 'TStringList', iptr);
    RegisterProperty('VideoExtensions', 'TStringList', iptr);
    RegisterProperty('TempSubfolder', 'string', iptrw);
    RegisterProperty('TempFile', 'string', iptrw);
    RegisterProperty('ConfigFile', 'string', iptrw);
    RegisterMethod('Procedure LoadConfig( aFileName : string)');
    RegisterMethod('Procedure SaveConfig( aFilename : string)');
    RegisterMethod('Procedure SetDefaultConfig');
  end;
end;

(*----------------------------------------------------------------------------*)
procedure SIRegister_ucEmutecaConfig(CL: TPSPascalCompiler);
begin
 CL.AddConstantN('krsIniSectionImages','String').SetString( 'Images');
 CL.AddConstantN('krsIniKeyImagesFolder','String').SetString( 'ImagesFolder');
 CL.AddConstantN('krsIniKeyDefaultImagesSubfolder','String').SetString( 'DefaultImagesSubfolder');
 CL.AddConstantN('krsIniKeyDefaultSystemImage','String').SetString( 'DefaultSystemImage');
 CL.AddConstantN('krsIniKeyDefaultSystemIcon','String').SetString( 'DefaultSystemIcon');
 CL.AddConstantN('krsIniKeyDefaultEmulatorImage','String').SetString( 'DefaultEmulatorImage');
 CL.AddConstantN('krsIniKeyDefaultEmulatorIcon','String').SetString( 'DefaultEmulatorIcon');
 CL.AddConstantN('krsIniKeyDefaultGameImage','String').SetString( 'DefaultGameImage');
 CL.AddConstantN('krsIniKeyDefaultGameIcon','String').SetString( 'DefaultGameIcon');
 CL.AddConstantN('krsIniSectionConfig','String').SetString( 'Config');
  SIRegister_cEmutecaConfig(CL);
end;

(* === run-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigConfigFile_W(Self: cEmutecaConfig; const T: string);
begin Self.ConfigFile := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigConfigFile_R(Self: cEmutecaConfig; var T: string);
begin T := Self.ConfigFile; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigTempFile_W(Self: cEmutecaConfig; const T: string);
begin Self.TempFile := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigTempFile_R(Self: cEmutecaConfig; var T: string);
begin T := Self.TempFile; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigTempSubfolder_W(Self: cEmutecaConfig; const T: string);
begin Self.TempSubfolder := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigTempSubfolder_R(Self: cEmutecaConfig; var T: string);
begin T := Self.TempSubfolder; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigVideoExtensions_R(Self: cEmutecaConfig; var T: TStringList);
begin T := Self.VideoExtensions; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigMusicExtensions_R(Self: cEmutecaConfig; var T: TStringList);
begin T := Self.MusicExtensions; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigImageExtensions_R(Self: cEmutecaConfig; var T: TStringList);
begin T := Self.ImageExtensions; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigTextExtensions_R(Self: cEmutecaConfig; var T: TStringList);
begin T := Self.TextExtensions; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigCompressedExtensions_R(Self: cEmutecaConfig; var T: TStringList);
begin T := Self.CompressedExtensions; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigGameGroupExt_W(Self: cEmutecaConfig; const T: string);
begin Self.GameGroupExt := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigGameGroupExt_R(Self: cEmutecaConfig; var T: string);
begin T := Self.GameGroupExt; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigGameDataExt_W(Self: cEmutecaConfig; const T: string);
begin Self.GameDataExt := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigGameDataExt_R(Self: cEmutecaConfig; var T: string);
begin T := Self.GameDataExt; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigSysStructFile_W(Self: cEmutecaConfig; const T: string);
begin Self.SysStructFile := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigSysStructFile_R(Self: cEmutecaConfig; var T: string);
begin T := Self.SysStructFile; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigSysSubfolder_W(Self: cEmutecaConfig; const T: string);
begin Self.SysSubfolder := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigSysSubfolder_R(Self: cEmutecaConfig; var T: string);
begin T := Self.SysSubfolder; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigSystemsFile_W(Self: cEmutecaConfig; const T: string);
begin Self.SystemsFile := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigSystemsFile_R(Self: cEmutecaConfig; var T: string);
begin T := Self.SystemsFile; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigEmulatorsFile_W(Self: cEmutecaConfig; const T: string);
begin Self.EmulatorsFile := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigEmulatorsFile_R(Self: cEmutecaConfig; var T: string);
begin T := Self.EmulatorsFile; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigVersionsFile_W(Self: cEmutecaConfig; const T: string);
begin Self.VersionsFile := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigVersionsFile_R(Self: cEmutecaConfig; var T: string);
begin T := Self.VersionsFile; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigParentsFile_W(Self: cEmutecaConfig; const T: string);
begin Self.ParentsFile := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigParentsFile_R(Self: cEmutecaConfig; var T: string);
begin T := Self.ParentsFile; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigDataFolder_W(Self: cEmutecaConfig; const T: string);
begin Self.DataFolder := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigDataFolder_R(Self: cEmutecaConfig; var T: string);
begin T := Self.DataFolder; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigGroupScriptsSubFolder_W(Self: cEmutecaConfig; const T: string);
begin Self.GroupScriptsSubFolder := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigGroupScriptsSubFolder_R(Self: cEmutecaConfig; var T: string);
begin T := Self.GroupScriptsSubFolder; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigGameScriptsSubFolder_W(Self: cEmutecaConfig; const T: string);
begin Self.GameScriptsSubFolder := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigGameScriptsSubFolder_R(Self: cEmutecaConfig; var T: string);
begin T := Self.GameScriptsSubFolder; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigGeneralScriptsSubFolder_W(Self: cEmutecaConfig; const T: string);
begin Self.GeneralScriptsSubFolder := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigGeneralScriptsSubFolder_R(Self: cEmutecaConfig; var T: string);
begin T := Self.GeneralScriptsSubFolder; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigScriptsFolder_W(Self: cEmutecaConfig; const T: string);
begin Self.ScriptsFolder := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigScriptsFolder_R(Self: cEmutecaConfig; var T: string);
begin T := Self.ScriptsFolder; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigEmulatorSubFolder_W(Self: cEmutecaConfig; const T: string);
begin Self.EmulatorSubFolder := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigEmulatorSubFolder_R(Self: cEmutecaConfig; var T: string);
begin T := Self.EmulatorSubFolder; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigTagSubFolder_W(Self: cEmutecaConfig; const T: string);
begin Self.TagSubFolder := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigTagSubFolder_R(Self: cEmutecaConfig; var T: string);
begin T := Self.TagSubFolder; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigYearSubFolder_W(Self: cEmutecaConfig; const T: string);
begin Self.YearSubFolder := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigYearSubFolder_R(Self: cEmutecaConfig; var T: string);
begin T := Self.YearSubFolder; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigCompanySubFolder_W(Self: cEmutecaConfig; const T: string);
begin Self.CompanySubFolder := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigCompanySubFolder_R(Self: cEmutecaConfig; var T: string);
begin T := Self.CompanySubFolder; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigCommonMediaFolder_W(Self: cEmutecaConfig; const T: string);
begin Self.CommonMediaFolder := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigCommonMediaFolder_R(Self: cEmutecaConfig; var T: string);
begin T := Self.CommonMediaFolder; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigz7GExecutable_W(Self: cEmutecaConfig; const T: string);
begin Self.z7GExecutable := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigz7GExecutable_R(Self: cEmutecaConfig; var T: string);
begin T := Self.z7GExecutable; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigz7CMExecutable_W(Self: cEmutecaConfig; const T: string);
begin Self.z7CMExecutable := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigz7CMExecutable_R(Self: cEmutecaConfig; var T: string);
begin T := Self.z7CMExecutable; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigz7Subfolder_W(Self: cEmutecaConfig; const T: string);
begin Self.z7Subfolder := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigz7Subfolder_R(Self: cEmutecaConfig; var T: string);
begin T := Self.z7Subfolder; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigToolsFolder_W(Self: cEmutecaConfig; const T: string);
begin Self.ToolsFolder := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigToolsFolder_R(Self: cEmutecaConfig; var T: string);
begin T := Self.ToolsFolder; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigDefaultGameIcon_W(Self: cEmutecaConfig; const T: string);
begin Self.DefaultGameIcon := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigDefaultGameIcon_R(Self: cEmutecaConfig; var T: string);
begin T := Self.DefaultGameIcon; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigDefaultGameImage_W(Self: cEmutecaConfig; const T: string);
begin Self.DefaultGameImage := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigDefaultGameImage_R(Self: cEmutecaConfig; var T: string);
begin T := Self.DefaultGameImage; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigDefaultEmulatorIcon_W(Self: cEmutecaConfig; const T: string);
begin Self.DefaultEmulatorIcon := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigDefaultEmulatorIcon_R(Self: cEmutecaConfig; var T: string);
begin T := Self.DefaultEmulatorIcon; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigDefaultEmulatorImage_W(Self: cEmutecaConfig; const T: string);
begin Self.DefaultEmulatorImage := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigDefaultEmulatorImage_R(Self: cEmutecaConfig; var T: string);
begin T := Self.DefaultEmulatorImage; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigDefaultSystemIcon_W(Self: cEmutecaConfig; const T: string);
begin Self.DefaultSystemIcon := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigDefaultSystemIcon_R(Self: cEmutecaConfig; var T: string);
begin T := Self.DefaultSystemIcon; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigDefaultSystemImage_W(Self: cEmutecaConfig; const T: string);
begin Self.DefaultSystemImage := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigDefaultSystemImage_R(Self: cEmutecaConfig; var T: string);
begin T := Self.DefaultSystemImage; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigDefaultImagesSubfolder_W(Self: cEmutecaConfig; const T: string);
begin Self.DefaultImagesSubfolder := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigDefaultImagesSubfolder_R(Self: cEmutecaConfig; var T: string);
begin T := Self.DefaultImagesSubfolder; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigImagesFolder_W(Self: cEmutecaConfig; const T: string);
begin Self.ImagesFolder := T; end;

(*----------------------------------------------------------------------------*)
procedure cEmutecaConfigImagesFolder_R(Self: cEmutecaConfig; var T: string);
begin T := Self.ImagesFolder; end;

(*----------------------------------------------------------------------------*)
procedure RIRegister_cEmutecaConfig(CL: TPSRuntimeClassImporter);
begin
  with CL.Add(cEmutecaConfig) do
  begin
    RegisterPropertyHelper(@cEmutecaConfigImagesFolder_R,@cEmutecaConfigImagesFolder_W,'ImagesFolder');
    RegisterPropertyHelper(@cEmutecaConfigDefaultImagesSubfolder_R,@cEmutecaConfigDefaultImagesSubfolder_W,'DefaultImagesSubfolder');
    RegisterPropertyHelper(@cEmutecaConfigDefaultSystemImage_R,@cEmutecaConfigDefaultSystemImage_W,'DefaultSystemImage');
    RegisterPropertyHelper(@cEmutecaConfigDefaultSystemIcon_R,@cEmutecaConfigDefaultSystemIcon_W,'DefaultSystemIcon');
    RegisterPropertyHelper(@cEmutecaConfigDefaultEmulatorImage_R,@cEmutecaConfigDefaultEmulatorImage_W,'DefaultEmulatorImage');
    RegisterPropertyHelper(@cEmutecaConfigDefaultEmulatorIcon_R,@cEmutecaConfigDefaultEmulatorIcon_W,'DefaultEmulatorIcon');
    RegisterPropertyHelper(@cEmutecaConfigDefaultGameImage_R,@cEmutecaConfigDefaultGameImage_W,'DefaultGameImage');
    RegisterPropertyHelper(@cEmutecaConfigDefaultGameIcon_R,@cEmutecaConfigDefaultGameIcon_W,'DefaultGameIcon');
    RegisterPropertyHelper(@cEmutecaConfigToolsFolder_R,@cEmutecaConfigToolsFolder_W,'ToolsFolder');
    RegisterPropertyHelper(@cEmutecaConfigz7Subfolder_R,@cEmutecaConfigz7Subfolder_W,'z7Subfolder');
    RegisterPropertyHelper(@cEmutecaConfigz7CMExecutable_R,@cEmutecaConfigz7CMExecutable_W,'z7CMExecutable');
    RegisterPropertyHelper(@cEmutecaConfigz7GExecutable_R,@cEmutecaConfigz7GExecutable_W,'z7GExecutable');
    RegisterPropertyHelper(@cEmutecaConfigCommonMediaFolder_R,@cEmutecaConfigCommonMediaFolder_W,'CommonMediaFolder');
    RegisterPropertyHelper(@cEmutecaConfigCompanySubFolder_R,@cEmutecaConfigCompanySubFolder_W,'CompanySubFolder');
    RegisterPropertyHelper(@cEmutecaConfigYearSubFolder_R,@cEmutecaConfigYearSubFolder_W,'YearSubFolder');
    RegisterPropertyHelper(@cEmutecaConfigTagSubFolder_R,@cEmutecaConfigTagSubFolder_W,'TagSubFolder');
    RegisterPropertyHelper(@cEmutecaConfigEmulatorSubFolder_R,@cEmutecaConfigEmulatorSubFolder_W,'EmulatorSubFolder');
    RegisterPropertyHelper(@cEmutecaConfigScriptsFolder_R,@cEmutecaConfigScriptsFolder_W,'ScriptsFolder');
    RegisterPropertyHelper(@cEmutecaConfigGeneralScriptsSubFolder_R,@cEmutecaConfigGeneralScriptsSubFolder_W,'GeneralScriptsSubFolder');
    RegisterPropertyHelper(@cEmutecaConfigGameScriptsSubFolder_R,@cEmutecaConfigGameScriptsSubFolder_W,'GameScriptsSubFolder');
    RegisterPropertyHelper(@cEmutecaConfigGroupScriptsSubFolder_R,@cEmutecaConfigGroupScriptsSubFolder_W,'GroupScriptsSubFolder');
    RegisterPropertyHelper(@cEmutecaConfigDataFolder_R,@cEmutecaConfigDataFolder_W,'DataFolder');
    RegisterPropertyHelper(@cEmutecaConfigParentsFile_R,@cEmutecaConfigParentsFile_W,'ParentsFile');
    RegisterPropertyHelper(@cEmutecaConfigVersionsFile_R,@cEmutecaConfigVersionsFile_W,'VersionsFile');
    RegisterPropertyHelper(@cEmutecaConfigEmulatorsFile_R,@cEmutecaConfigEmulatorsFile_W,'EmulatorsFile');
    RegisterPropertyHelper(@cEmutecaConfigSystemsFile_R,@cEmutecaConfigSystemsFile_W,'SystemsFile');
    RegisterPropertyHelper(@cEmutecaConfigSysSubfolder_R,@cEmutecaConfigSysSubfolder_W,'SysSubfolder');
    RegisterPropertyHelper(@cEmutecaConfigSysStructFile_R,@cEmutecaConfigSysStructFile_W,'SysStructFile');
    RegisterPropertyHelper(@cEmutecaConfigGameDataExt_R,@cEmutecaConfigGameDataExt_W,'GameDataExt');
    RegisterPropertyHelper(@cEmutecaConfigGameGroupExt_R,@cEmutecaConfigGameGroupExt_W,'GameGroupExt');
    RegisterPropertyHelper(@cEmutecaConfigCompressedExtensions_R,nil,'CompressedExtensions');
    RegisterPropertyHelper(@cEmutecaConfigTextExtensions_R,nil,'TextExtensions');
    RegisterPropertyHelper(@cEmutecaConfigImageExtensions_R,nil,'ImageExtensions');
    RegisterPropertyHelper(@cEmutecaConfigMusicExtensions_R,nil,'MusicExtensions');
    RegisterPropertyHelper(@cEmutecaConfigVideoExtensions_R,nil,'VideoExtensions');
    RegisterPropertyHelper(@cEmutecaConfigTempSubfolder_R,@cEmutecaConfigTempSubfolder_W,'TempSubfolder');
    RegisterPropertyHelper(@cEmutecaConfigTempFile_R,@cEmutecaConfigTempFile_W,'TempFile');
    RegisterPropertyHelper(@cEmutecaConfigConfigFile_R,@cEmutecaConfigConfigFile_W,'ConfigFile');
    RegisterMethod(@cEmutecaConfig.LoadConfig, 'LoadConfig');
    RegisterMethod(@cEmutecaConfig.SaveConfig, 'SaveConfig');
    RegisterMethod(@cEmutecaConfig.SetDefaultConfig, 'SetDefaultConfig');
  end;
end;

(*----------------------------------------------------------------------------*)
procedure RIRegister_ucEmutecaConfig(CL: TPSRuntimeClassImporter);
begin
  RIRegister_cEmutecaConfig(CL);
end;

 
 
{ TPSImport_ucEmutecaConfig }
(*----------------------------------------------------------------------------*)
procedure TPSImport_ucEmutecaConfig.CompileImport1(CompExec: TPSScript);
begin
  SIRegister_ucEmutecaConfig(CompExec.Comp);
end;
(*----------------------------------------------------------------------------*)
procedure TPSImport_ucEmutecaConfig.ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter);
begin
  RIRegister_ucEmutecaConfig(ri);
end;
(*----------------------------------------------------------------------------*)
 
 
end.
