# Plugins
# -------
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  
# Otras interesantes
# baseurl: /Emuteca (dirección base)
  
# Mis variables
# -------------
title: "Emuteca"
EmuVer: 0.8
description: > # > Para multilíneas
  "Frontend para juegos y emuladores."
logo: "/Emuteca/img/Icon.png"
author: "Chixpy"
lang: "es"
date_format: "%e de %B de %Y"